// Original Reading and Writing item bank. Options list the correct answer FIRST;
// the generator shuffles and letters them. Passages use [[blank]] for fill-ins,
// **bold**, __underline__ and blank lines for paragraphs.

export const STEMS = {
  vocab: 'Which choice completes the text with the most logical and precise word or phrase?',
  purpose: 'Which choice best states the main purpose of the text?',
  'main-idea': 'Which choice best states the main idea of the text?',
  function: 'Which choice best describes the function of the underlined sentence in the text as a whole?',
  'cross-text': 'Based on the texts, how would the author of Text 2 most likely respond to the claim made in Text 1?',
  inference: 'Which choice most logically completes the text?',
  evidence: 'Which finding, if true, would most directly support the researchers’ hypothesis?',
  data: 'Which choice most effectively uses data from the table to complete the statement?',
  sec: 'Which choice completes the text so that it conforms to the conventions of Standard English?',
  transition: 'Which choice completes the text with the most logical transition?',
  synthesis: (goal) => `The student wants to ${goal}. Which choice most effectively uses relevant information from the notes to accomplish this goal?`,
}

export function domainFor(skill) {
  if (['vocab', 'purpose', 'function', 'cross-text'].includes(skill)) return 'Craft and Structure'
  if (['main-idea', 'inference', 'evidence', 'data'].includes(skill)) return 'Information and Ideas'
  if (skill === 'sec') return 'Standard English Conventions'
  return 'Expression of Ideas'
}

export const SKILL_NAMES = {
  vocab: 'Words in Context', purpose: 'Text Structure and Purpose', function: 'Text Structure and Purpose', 'cross-text': 'Cross-Text Connections',
  'main-idea': 'Central Ideas and Details', inference: 'Inferences', evidence: 'Command of Evidence', data: 'Command of Evidence (Quantitative)',
  sec: 'Boundaries and Form, Structure, and Sense', transition: 'Transitions', synthesis: 'Rhetorical Synthesis',
}

const V = (passage, options, difficulty, explanation) => ({ passage, options, difficulty, explanation })
export const vocabItems = [
  V('Because the coral samples had been collected over four decades, the marine biologist was able to [[blank]] long-term shifts in ocean temperature that a single expedition could never have revealed.', ['document', 'postpone', 'exaggerate', 'conceal'], 'easy', 'The samples span decades, so they let the biologist record, or document, long-term change.'),
  V('Although the novelist’s early drafts were sprawling, her editor praised the final manuscript for its [[blank]]: not a single scene felt unnecessary.', ['economy', 'ambiguity', 'grandeur', 'monotony'], 'medium', '“Not a single scene felt unnecessary” describes economy, the efficient use of material.'),
  V('The committee’s report was deliberately [[blank]], offering no firm recommendation so that each department could interpret the findings in its own way.', ['noncommittal', 'exhaustive', 'belligerent', 'candid'], 'hard', 'A report that avoids any firm recommendation is noncommittal.'),
  V('Migratory monarch butterflies are remarkably [[blank]] navigators, returning to the same Mexican forests their great-grandparents left months earlier.', ['precise', 'reluctant', 'erratic', 'nocturnal'], 'easy', 'Returning to the very same forests shows precision in navigation.'),
  V('Historians once regarded the merchant’s diary as [[blank]], but the discovery of matching customs records has since confirmed nearly every entry.', ['unreliable', 'invaluable', 'exhaustive', 'conventional'], 'medium', 'The contrast (“but…confirmed”) signals that historians previously doubted the diary, so “unreliable” fits.'),
  V('The architect’s proposal was praised for [[blank]] the neighborhood’s industrial past with modern needs: the old brick warehouse now houses a library.', ['reconciling', 'abandoning', 'obscuring', 'replicating'], 'medium', 'Combining the past with modern needs is reconciling the two.'),
  V('Rather than [[blank]] the criticism, the mayor invited the reporters to tour the new water treatment facility themselves.', ['dismissing', 'soliciting', 'amplifying', 'anticipating'], 'easy', 'Inviting reporters to see for themselves is the opposite of dismissing criticism.'),
  V('The physicist’s lecture was so [[blank]] that even audience members with no scientific training left with a clear picture of how gravitational waves are detected.', ['lucid', 'protracted', 'esoteric', 'tentative'], 'medium', 'A lecture that gives nonspecialists a clear picture is lucid, or clear.'),
  V('Because the cave paintings are extremely [[blank]], visitors are limited to a replica gallery nearby, where humidity from human breath cannot damage the pigments.', ['fragile', 'abundant', 'vivid', 'remote'], 'easy', 'The concern about damage from humidity shows the paintings are fragile.'),
  V('The senator’s remarks were widely read as [[blank]]: she praised the bill in public while privately urging colleagues to delay the vote.', ['duplicitous', 'magnanimous', 'prescient', 'diplomatic'], 'hard', 'Saying one thing publicly and the opposite privately is duplicitous.'),
  V('Early radio broadcasts were [[blank]] events; families gathered around a single set, and a program’s arrival was announced like a visiting dignitary.', ['communal', 'solitary', 'clandestine', 'commercial'], 'medium', 'Families gathering together makes the broadcasts communal, or shared.'),
  V('The engineers [[blank]] the bridge’s original design, adding steel cables that carry loads the nineteenth-century builders never imagined.', ['augmented', 'dismantled', 'ridiculed', 'duplicated'], 'medium', 'Adding cables that increase capacity augments, or adds to, the design.'),
  V('The playwright’s dialogue is famously [[blank]]; characters interrupt, trail off, and talk past one another in a way that mirrors real conversation.', ['naturalistic', 'florid', 'didactic', 'formulaic'], 'hard', 'Dialogue that mirrors real conversation is naturalistic.'),
  V('In the drought-prone region, farmers have long practiced water [[blank]], storing every drop from the brief rainy season in underground cisterns.', ['conservation', 'consumption', 'diversion', 'purification'], 'easy', 'Storing every drop of water is conservation.'),
  V('The astronomer’s claim was initially met with [[blank]], but subsequent observations by three independent teams silenced most doubters.', ['skepticism', 'enthusiasm', 'indifference', 'nostalgia'], 'easy', '“Silenced most doubters” implies the initial reaction was skepticism.'),
  V('Instead of a single [[blank]] narrator, the novel rotates among six characters, each of whom reveals details the others cannot know.', ['omniscient', 'unreliable', 'anonymous', 'peripheral'], 'hard', 'An omniscient narrator knows everything; the novel instead uses limited narrators.'),
  V('The tiny electronic tags are [[blank]] enough that researchers can attach them to bumblebees without affecting the insects’ flight.', ['lightweight', 'durable', 'conspicuous', 'expensive'], 'easy', 'Not affecting flight means the tags are lightweight.'),
  V('By the 1920s, the once-[[blank]] pastime of listening to jazz records had become a mainstream feature of urban life.', ['marginal', 'ubiquitous', 'lucrative', 'refined'], 'medium', 'The contrast with “mainstream” requires a word meaning fringe or marginal.'),
  V('The translator’s notes [[blank]] the poem’s many puns, explaining wordplay that would otherwise be lost on English readers.', ['elucidate', 'suppress', 'invent', 'dismiss'], 'medium', 'Notes that explain wordplay elucidate, or clarify, it.'),
  V('Although the two species look nearly identical, their calls are so [[blank]] that ornithologists can tell them apart from a recording alone.', ['distinctive', 'melodious', 'infrequent', 'subdued'], 'easy', 'Calls that allow identification are distinctive.'),
  V('The study’s findings are [[blank]] at best: the sample was small, and the researchers themselves caution against drawing firm conclusions.', ['provisional', 'definitive', 'controversial', 'redundant'], 'medium', 'Findings that should not be treated as firm are provisional, or tentative.'),
  V('Fungi play an [[blank]] role in forest ecosystems, quietly breaking down fallen trees and returning nutrients to the soil.', ['indispensable', 'ornamental', 'adversarial', 'intermittent'], 'medium', 'Recycling nutrients is an essential, or indispensable, function.'),
  V('The museum’s new wing is intentionally [[blank]], its plain concrete walls designed to keep attention on the artworks rather than the architecture.', ['unobtrusive', 'opulent', 'cavernous', 'symmetrical'], 'hard', 'Architecture designed not to draw attention is unobtrusive.'),
  V('Faced with [[blank]] evidence—some records supporting the date, others contradicting it—the archivists declined to assign the letter to a specific year.', ['conflicting', 'compelling', 'corroborating', 'sparse'], 'medium', 'Records that both support and contradict a date are conflicting.'),
  V('The coach’s halftime speech was brief but [[blank]]; the team returned to the field with visibly renewed energy.', ['galvanizing', 'meandering', 'conciliatory', 'perfunctory'], 'hard', 'A speech that renews energy is galvanizing.'),
  V('Glaciers [[blank]] the valley over thousands of years, grinding its floor smooth and leaving steep walls on either side.', ['sculpted', 'flooded', 'populated', 'concealed'], 'easy', 'Grinding and shaping a valley is sculpting it.'),
  V('The chef is known for her [[blank]] approach to tradition: she honors classic techniques while freely substituting local ingredients.', ['flexible', 'rigid', 'dismissive', 'secretive'], 'easy', 'Honoring tradition while adapting it is a flexible approach.'),
  V('Because the manuscript’s ink has [[blank]] over the centuries, curators now rely on ultraviolet imaging to read the faintest passages.', ['faded', 'thickened', 'brightened', 'spread'], 'easy', 'Ink that requires special imaging to read has faded.'),
  V('Critics who called the early telephone a mere [[blank]] were soon proved wrong; within a decade it had become essential to commerce.', ['novelty', 'necessity', 'milestone', 'monopoly'], 'medium', 'The critics underestimated the telephone, treating it as a passing novelty.'),
  V('The negotiators’ [[blank]] on the final point—neither side would yield on fishing rights—delayed the treaty for another year.', ['impasse', 'consensus', 'collaboration', 'compromise'], 'hard', 'Neither side yielding describes an impasse, or deadlock.'),
  V('The poet’s later work is notably more [[blank]] than her early verse, trading long descriptive passages for poems of a few sharp lines.', ['spare', 'elaborate', 'sentimental', 'accessible'], 'hard', 'Poems reduced to a few lines are spare, or economical.'),
  V('Because the virus mutates so [[blank]], vaccine formulas must be updated each year to match the strains in circulation.', ['rapidly', 'rarely', 'predictably', 'harmlessly'], 'easy', 'Yearly updates are needed because the virus changes rapidly.'),
]

const R = (skill, passage, options, difficulty, explanation, extra = {}) => ({ skill, passage, options, difficulty, explanation, ...extra })
export const readingItems = [
  // ---- Purpose (Craft and Structure)
  R('purpose', 'The following text is adapted from a 2021 article about seed libraries.\n\nAt the Millbrook Public Library, patrons can check out something besides books: packets of vegetable and flower seeds. Gardeners take the seeds home, grow the plants, and, if they wish, return a portion of the harvested seeds at the end of the season. The program began with a single filing cabinet and now stocks more than two hundred varieties, many of them heirloom strains that commercial catalogs no longer carry.', ['To describe how a seed-lending program works and how it has grown', 'To argue that libraries should stop lending books in favor of seeds', 'To explain why heirloom seeds are disappearing from commercial catalogs', 'To compare the Millbrook program with programs in other towns'], 'easy', 'The text explains the program’s mechanics and notes its growth from one cabinet to two hundred varieties.'),
  R('purpose', 'The following text is from a short story. The narrator, Marguerite, has returned to her childhood home after many years.\n\nThe kitchen was smaller than I remembered, and the window over the sink, which had once framed an entire orchard, now showed only a slice of fence. I ran my hand along the counter and found the burn mark my brother had left with a pot of caramel. It was still there, a small brown continent, and for a moment the room seemed to expand again to its old size.', ['To convey the narrator’s shifting perception of a familiar place', 'To explain why the narrator left home as a child', 'To describe the process of renovating an old kitchen', 'To criticize the narrator’s brother for his carelessness'], 'medium', 'The passage tracks how the kitchen seems smaller, then “expands again” in the narrator’s mind, emphasizing perception.'),
  R('purpose', 'Ecologists studying urban coyotes have typically relied on radio collars, which are expensive and can be fitted only to the handful of animals researchers manage to trap. A team in Chicago instead analyzed thousands of photographs submitted by residents through a smartphone app. By matching the timestamps and locations of the images against a city map, the team reconstructed the movements of dozens of coyotes without handling a single animal.', ['To describe an alternative research method and its advantage over a conventional one', 'To argue that radio collars harm the animals that wear them', 'To encourage city residents to avoid contact with coyotes', 'To question whether residents’ photographs are accurate'], 'hard', 'The text contrasts collars with photo analysis and highlights the new method’s advantage: no trapping required.'),
  // ---- Function (Craft and Structure)
  R('function', 'Many nineteenth-century lighthouses were painted with bold stripes or checkerboards. __These patterns were not decorative but functional: each lighthouse’s design was unique, so a sailor who spotted one in daylight could identify it and fix the ship’s position on a chart.__ Even today, when satellites handle most navigation, coastal authorities preserve the historic patterns, partly because mariners still use them as a backup.', ['It explains the practical reason behind a feature introduced in the previous sentence.', 'It introduces a counterargument that the rest of the text refutes.', 'It describes how modern navigation has made lighthouses obsolete.', 'It offers an example of a lighthouse that is no longer preserved.'], 'medium', 'The underlined sentence explains why the stripes mentioned in the first sentence existed.'),
  R('function', 'Composer Florence Price wrote more than three hundred works, yet for decades most were thought lost. __In 2009, renovators of an abandoned house outside Chicago discovered boxes of her manuscripts in the attic.__ The find has fueled a revival: orchestras that had never programmed Price now perform her symphonies regularly, and scholars are editing dozens of previously unknown pieces for publication.', ['It identifies the event that made the revival described in the next sentence possible.', 'It suggests that Price deliberately hid her manuscripts from the public.', 'It summarizes the main features of Price’s musical style.', 'It argues that orchestras were wrong to ignore Price’s work.'], 'medium', 'The discovery of the manuscripts is the event that “fueled a revival.”'),
  // ---- Cross-text (Craft and Structure)
  R('cross-text', '**Text 1**\n\nThe Antikythera mechanism, a bronze device recovered from a shipwreck near Greece, has been called the world’s first analog computer. Its dozens of interlocking gears modeled the motions of the Sun and Moon with a sophistication that would not reappear in Europe for more than a thousand years. Some historians conclude that the device must have been a one-of-a-kind creation by an exceptional genius.\n\n**Text 2**\n\nThe craftsmanship of the Antikythera mechanism is undeniably impressive, but its very refinement argues against its being unique. Gears cut this precisely are the product of a tradition, not a single inspired afternoon. The device almost certainly had predecessors and contemporaries; they simply have not survived, because bronze was routinely melted down and reused.', ['By arguing that the mechanism’s sophistication implies it was one of many similar devices, not a singular creation', 'By agreeing that the mechanism was probably built by a single genius working alone', 'By questioning whether the mechanism really modeled the motions of the Sun and Moon', 'By suggesting that the mechanism was built more recently than Text 1 claims'], 'hard', 'Text 2 says the refinement “argues against its being unique” and that the device had predecessors and contemporaries.'),
  R('cross-text', '**Text 1**\n\nCity governments have embraced “pocket parks”—tiny green spaces squeezed between buildings—as a low-cost way to improve residents’ well-being. Studies report that people who live within a short walk of any park, regardless of its size, report lower stress than those who do not.\n\n**Text 2**\n\nAccess to green space matters, but so does what people can do there. Sociologist Dana Whitfield tracked how residents used twelve pocket parks over a summer and found that most visits lasted under three minutes. Parks too small for sitting, playing, or gathering, she argues, may improve a neighborhood’s appearance without changing how residents actually spend their time.', ['By cautioning that proximity to a park does not guarantee the benefits associated with using one', 'By denying that any relationship exists between parks and stress levels', 'By recommending that cities build larger parks in place of pocket parks', 'By agreeing that pocket parks are the most cost-effective option available to cities'], 'medium', 'Text 2 accepts that access matters but stresses that tiny parks may not change how residents spend time.'),
  R('cross-text', '**Text 1**\n\nHandwriting instruction is a poor use of classroom hours. Nearly all writing that today’s students will do as adults will be typed, and time spent perfecting cursive loops could be devoted to composition, reading, or keyboarding skills.\n\n**Text 2**\n\nIn a series of experiments, psychologist Lena Ortiz asked children to learn unfamiliar letters either by writing them by hand or by typing them. Children who wrote by hand recognized the letters faster afterward and showed more activity in brain regions associated with reading. Whether or not adults ever write in cursive, the act of forming letters appears to build the neural foundations of literacy.', ['By suggesting that handwriting instruction has benefits for reading that Text 1 does not consider', 'By agreeing that keyboarding should replace handwriting in elementary classrooms', 'By arguing that cursive is more useful to adults than Text 1 acknowledges', 'By claiming that typing offers the same benefits as handwriting for young children'], 'medium', 'Text 2 presents evidence that forming letters by hand supports reading, a benefit Text 1 ignores.'),
  // ---- Main idea (Information and Ideas)
  R('main-idea', 'The following text is adapted from a 1913 essay by naturalist Anna Botsford Comstock.\n\nThe child who has learned to know the birds of the dooryard has a friend in every tree. She will not need to be told that the world is beautiful, for she has found it so; and when the years bring cares, she will have a refuge that costs nothing and is never closed. Nature study is not a lesson to be recited; it is a habit of attention that, once formed, enriches a whole life.', ['Learning to observe nature in childhood provides lasting rewards.', 'Children should memorize the names of the birds near their homes.', 'Formal lessons are the best way to teach children about the natural world.', 'Adults rarely find time to appreciate the beauty of nature.'], 'easy', 'The text argues that a childhood habit of attention to nature “enriches a whole life.”'),
  R('main-idea', 'For centuries, the indigo dye used in textiles came from plants, and producing it was laborious: leaves were fermented in vats, then the liquid was beaten with paddles for hours to oxidize the dye. When a synthetic version became available in 1897, plant-based indigo nearly vanished within a decade. Recently, however, small farms in South Carolina and Tennessee have revived the crop, selling natural indigo to designers who prize its uneven, hand-made appearance.', ['Natural indigo, largely displaced by a synthetic alternative, is being produced again on a small scale.', 'Synthetic indigo is inferior in quality to dye made from plants.', 'The process of making plant-based indigo has become much less laborious.', 'Designers have stopped using synthetic dyes in their textiles.'], 'medium', 'The text traces indigo’s decline after synthetic dye and its recent small-scale revival.'),
  R('main-idea', 'Octopuses have been observed collecting coconut-shell halves, carrying them across the seafloor, and later assembling the halves into a shelter. Because the animals gain nothing from the shells while transporting them—the awkward load actually slows their escape from predators—researchers argue that the behavior meets a strict definition of tool use: the octopus bears a present cost for a future benefit.', ['The octopus’s handling of coconut shells qualifies as tool use because it involves accepting a cost now for a later benefit.', 'Octopuses use coconut shells primarily to escape from predators more quickly.', 'Researchers disagree about whether octopuses are capable of planning ahead.', 'Coconut shells are the only objects octopuses have been seen carrying.'], 'medium', 'The text explains the reasoning that the behavior meets a strict definition of tool use.'),
  // ---- Inference (Information and Ideas)
  R('inference', 'Bats that roost in large colonies are exposed to many more parasites than solitary bats are. Yet colonial species do not show higher rates of parasite-borne illness. Biologists who compared the two groups found that colonial bats spend far more time grooming, both themselves and one another, than solitary bats do. This suggests that [[blank]]', ['the extra grooming in colonies offsets the increased exposure to parasites.', 'solitary bats are more vulnerable to parasites than colonial bats are.', 'parasites are unable to survive in large bat colonies.', 'colonial bats have stronger immune systems than solitary bats.'], 'medium', 'Higher exposure without higher illness, plus more grooming, implies grooming compensates for exposure.'),
  R('inference', 'A publisher tested two covers for the same mystery novel: one showing a dark alley, the other a bright seaside town. In bookstores, the alley cover sold better; online, where shoppers see only a small thumbnail image, the seaside cover sold better. The publisher concluded that [[blank]]', ['the effectiveness of a cover design can depend on the setting in which customers encounter it.', 'mystery readers generally prefer bright colors to dark ones.', 'online shoppers are less interested in mystery novels than bookstore shoppers are.', 'the novel would have sold better with no cover image at all.'], 'easy', 'Each cover won in a different setting, so effectiveness depends on context.'),
  R('inference', 'The Roman writer Pliny the Elder described a purple dye so costly that a pound of dyed wool sold for more than a year’s wages. Chemists who recently reproduced the dye from its source—a secretion of Mediterranean sea snails—found that about ten thousand snails were needed to color a single garment. Given this, it is reasonable to conclude that [[blank]]', ['the dye’s high price reflected the enormous quantity of raw material it required.', 'Pliny greatly exaggerated the cost of the dye in his account.', 'purple garments were commonly worn by ordinary Romans.', 'the sea snails were more abundant in Roman times than they are today.'], 'medium', 'Ten thousand snails per garment explains the extraordinary expense Pliny described.'),
  R('inference', 'Volunteers in a sleep study were asked to memorize a list of word pairs in the evening. Half were then allowed to sleep normally; the other half were kept awake until morning. When tested the next day, the sleep group recalled about 40 percent more pairs. When both groups were tested again a week later, after every participant had slept normally each night, the gap remained. This result implies that [[blank]]', ['sleep on the night immediately after learning plays a role in memory that later sleep cannot fully replace.', 'the volunteers who stayed awake were unable to learn new word pairs.', 'memory for word pairs improves the longer a person stays awake.', 'a single night of sleep loss has no lasting effect on memory.'], 'hard', 'Because the gap persisted after a week of normal sleep, the first night’s sleep had a special, unrecoverable effect.'),
  R('inference', 'Wind turbines are usually painted white to blend with the sky, but a Norwegian wind farm painted one blade of each turbine black. Over the following years, bird collisions at those turbines fell by roughly 70 percent compared with all-white turbines nearby. The researchers suggest that [[blank]]', ['a single dark blade makes the spinning rotor easier for birds to see and avoid.', 'birds are attracted to white objects and repelled by black ones.', 'the black paint reduced the speed at which the turbine blades rotated.', 'birds had stopped flying near the wind farm altogether.'], 'easy', 'A visible contrasting blade would explain why birds avoided the rotor.'),
  // ---- Evidence (Information and Ideas)
  R('evidence', 'Some archaeologists hypothesize that a cluster of stone structures in the Arabian desert served as traps for herding wild gazelles, not as dwellings, as earlier scholars assumed. The structures consist of two long, low walls that converge toward a circular enclosure with a pit at its center.', ['Excavations of the pits yield large numbers of gazelle bones but almost no household objects such as pottery or hearths.', 'The stone walls are made of the same rock found throughout the surrounding desert.', 'Similar circular enclosures elsewhere in the region contain evidence of long-term human habitation.', 'The structures are located near seasonal water sources that gazelles are known to visit.'], 'medium', 'Gazelle bones without household objects support the trap hypothesis over the dwelling hypothesis.'),
  R('evidence', 'Certain pitcher plants are thought to attract insect prey with their scent. Botanist Amara Okafor hypothesizes that the plants also “advertise” themselves visually, using ultraviolet patterns on the pitcher rim that are invisible to humans but visible to many insects.', ['Pitchers whose rims are coated with a substance that blocks ultraviolet light capture significantly fewer insects than untreated pitchers, even though their scent is unchanged.', 'Pitcher plants growing in shaded locations capture fewer insects than those growing in full sun.', 'Insects that visit pitcher plants are also attracted to nearby flowers with strong scents.', 'The rims of pitcher plants are slippery, causing insects that land there to fall into the pitcher.'], 'hard', 'Blocking UV while keeping scent constant isolates the visual signal; fewer captures support the hypothesis.'),
  R('evidence', 'Economists have proposed that medieval trade fairs declined not because of warfare, as commonly believed, but because merchants developed reliable long-distance credit arrangements that made traveling to fairs unnecessary.', ['Records show that the number of merchants attending fairs fell most sharply in peaceful regions where banking networks expanded fastest.', 'Several fairs were held in towns that had recently been damaged in battles.', 'Merchants who attended fairs typically traveled in armed convoys for protection.', 'The goods sold at fairs became more expensive in the years before the fairs declined.'], 'medium', 'Decline in peaceful regions with growing credit networks links the decline to credit rather than war.'),
  R('evidence', 'Linguists have hypothesized that speakers of languages with obligatory future tense (such as English, which requires “will” for future events) think about the future as more distant from the present than speakers of languages that use the present tense for future events.', ['In an experiment, speakers of obligatory-future languages estimated that events scheduled a month away would occur later than speakers of other languages did.', 'Speakers of obligatory-future languages tend to learn other languages more slowly.', 'Most languages spoken in Europe have an obligatory future tense.', 'Speakers of all languages studied reported thinking about the future several times a day.'], 'hard', 'The estimate difference directly measures perceived distance of future events.'),
  // ---- Data (Information and Ideas)
  R('data', 'A city surveyed residents about how they commute to work and repeated the survey five years later. A transportation planner noted that the share of residents who commute by bicycle [[blank]]', ['increased from 6 percent to 11 percent, while the share who drive alone decreased from 58 percent to 49 percent.', 'increased from 6 percent to 11 percent, while the share who use public transit decreased.', 'remained the same, while the share who drive alone decreased from 58 percent to 49 percent.', 'was the largest of any commuting method in the second survey.'], 'medium', 'The table shows bicycling rising 6 → 11 percent and driving alone falling 58 → 49 percent.', { table: { caption: 'Commuting Method by Share of Residents', headers: ['Method', 'Year 1', 'Year 6'], rows: [['Drive alone', '58%', '49%'], ['Public transit', '20%', '23%'], ['Bicycle', '6%', '11%'], ['Walk', '9%', '10%'], ['Other', '7%', '7%']] } }),
  R('data', 'Researchers measured the average mass of four species of songbird before and after a harsh winter. They found that the species with the largest average mass, the [[blank]]', ['blue jay, lost about 3 grams, a smaller proportion of its body mass than any other species lost.', 'blue jay, lost more grams than any other species and also the largest proportion of its mass.', 'chickadee, lost about 1 gram over the winter.', 'cardinal, gained mass over the course of the winter.'], 'medium', 'The blue jay is heaviest (86 → 83 g); its 3 g loss is the smallest fraction of body mass.', { table: { caption: 'Average Mass Before and After Winter (grams)', headers: ['Species', 'Before', 'After'], rows: [['Chickadee', '12', '10'], ['Cardinal', '45', '41'], ['Blue jay', '86', '83'], ['Sparrow', '28', '25']] } }),
  R('data', 'A student compared how long four brands of rechargeable battery powered an identical flashlight. She concluded that Brand C offered the best value, since [[blank]]', ['it lasted 14 hours, only 1 hour less than the longest-lasting brand, while costing \\$6 less than that brand.', 'it lasted longer than every other brand tested.', 'it was the least expensive brand and lasted 11 hours.', 'it cost the same as Brand A but lasted 4 hours longer.'], 'easy', 'Brand C: 14 hours at \\$12 versus Brand D’s 15 hours at \\$18.', { table: { caption: 'Battery Performance', headers: ['Brand', 'Price', 'Hours of light'], rows: [['A', '\\$9', '11'], ['B', '\\$10', '12'], ['C', '\\$12', '14'], ['D', '\\$18', '15']] } }),
  R('data', 'The table shows the number of visitors to a national park during three months in two consecutive years. A park ranger observed that in every month, [[blank]]', ['visitor numbers were higher in Year 2 than in Year 1, with the largest increase occurring in July.', 'visitor numbers were higher in Year 2 than in Year 1, with the largest increase occurring in June.', 'visitor numbers in Year 2 were at least double those in Year 1.', 'July had fewer visitors than August.'], 'easy', 'All three months rose; July’s increase (60 → 78 thousand) is the largest.', { table: { caption: 'Park Visitors (thousands)', headers: ['Month', 'Year 1', 'Year 2'], rows: [['June', '42', '51'], ['July', '60', '78'], ['August', '55', '63']] } }),
]

const G = (pre, post, options, skill, difficulty, explanation) => ({ pre, post, options, skill, difficulty, explanation })
export const grammarFrames = [
  G('The collection of letters, photographs, and ledgers ', ' now stored at the county museum.', ['is', 'are', 'were', 'have been'], 'subject-verb agreement', 'easy', 'The subject is the singular noun “collection,” so the verb must be singular: “is.”'),
  G('Each of the three telescopes on the mountain ', ' a mirror more than eight meters across.', ['has', 'have', 'having', 'are having'], 'subject-verb agreement', 'medium', '“Each” is singular, so “has” is required.'),
  G('The engineer who designed the suspension cables, along with her two assistants, ', ' honored at the ceremony.', ['was', 'were', 'are', 'being'], 'subject-verb agreement', 'hard', 'The subject is “the engineer”; the phrase set off by commas does not change its number.'),
  G('Neither the mayor nor the council members ', ' willing to postpone the vote.', ['were', 'was', 'is', 'has been'], 'subject-verb agreement', 'hard', 'With “neither…nor,” the verb agrees with the nearer subject, “members,” which is plural.'),
  G('The orchestra tuned its instruments, the lights ', ' and the audience fell silent.', ['dimmed,', 'dimmed;', 'dimmed', 'dimmed—'], 'punctuation in series', 'easy', 'Items in a series of three independent clauses are separated by commas: “tuned…, the lights dimmed, and the audience fell silent.”'),
  G('The expedition carried three months of ', ' the journey took nearly five.', ['supplies; however,', 'supplies, however,', 'supplies however,', 'supplies; however'], 'boundaries', 'medium', 'Two independent clauses joined by “however” require a semicolon before and a comma after the adverb.'),
  G('The reef’s recovery has been ', ' scientists remain optimistic.', ['slow, but', 'slow but', 'slow, and so', 'slow; but'], 'boundaries', 'easy', 'Two independent clauses joined by “but” need a comma before the conjunction.'),
  G('Painter Alma Thomas, who did not exhibit her work until she was in her ', ' became one of the most celebrated abstract artists of her generation.', ['sixties,', 'sixties', 'sixties;', 'sixties—'], 'boundaries', 'medium', 'The nonessential clause beginning with “who” must be closed with a comma.'),
  G('The lab’s new ', ' can detect a single molecule of the compound in a liter of water.', ['sensor', 'sensor,', 'sensor;', 'sensor, which'], 'boundaries', 'easy', 'No punctuation should separate a subject from its verb.'),
  G('The recipe calls for two ', ' butter, and a pinch of salt.', ['ingredients: flour,', 'ingredients, flour,', 'ingredients; flour,', 'ingredients flour,'], 'punctuation', 'medium', 'A colon introduces the list that follows a complete clause.'),
  G('The ', ' first novel sold poorly, but her second became a bestseller.', ['author’s', 'authors', 'authors’', 'author'], 'possessives', 'easy', 'One author possesses the novel: “author’s.”'),
  G('Both ', ' proposals were rejected by the planning board.', ['architects’', 'architect’s', 'architects', 'architects’s'], 'possessives', 'medium', 'Two architects possess the proposals: the plural possessive “architects’.”'),
  G('The committee will announce ', ' decision after reviewing the final report.', ['its', 'it’s', 'their', 'there'], 'pronouns', 'easy', '“Committee” is singular, and the possessive pronoun is “its” (no apostrophe).'),
  G('Researchers tagged the sea turtles and tracked ', ' migration across the Atlantic.', ['their', 'its', 'there', 'they’re'], 'pronouns', 'easy', 'The plural antecedent “turtles” requires the plural possessive “their.”'),
  G('After the storm passed, the volunteers ', ' the debris from the beach and hauled it to the recycling center.', ['cleared', 'clearing', 'having cleared', 'to clear'], 'verb forms', 'easy', 'The sentence needs a main verb parallel with “hauled”: “cleared.”'),
  G('By the time the ship reached port, the crew ', ' at sea for eleven weeks.', ['had been', 'has been', 'was being', 'is'], 'verb tense', 'medium', 'The past perfect “had been” indicates an action completed before another past event.'),
  G('The documentary, ', ' by a team of former park rangers, follows a single wolf pack for a year.', ['produced', 'producing', 'which producing', 'it was produced'], 'modifiers', 'medium', 'The participle “produced” correctly modifies “documentary.”'),
  G('', ' the manuscript for errors, the editor returned it to the author with a list of suggestions.', ['Having checked', 'Checking of', 'To have been checked', 'While checking, and'], 'modifiers', 'hard', 'The participial phrase must logically describe the editor, who checked the manuscript.'),
  G('Coffee cultivation spread from Ethiopia to ', ' by the fifteenth century, it was being grown throughout the region.', ['Yemen;', 'Yemen,', 'Yemen', 'Yemen and'], 'boundaries', 'medium', 'Two independent clauses must be joined by a semicolon, not a comma alone.'),
  G('The mural depicts three generations of a farming ', ' grandparents, parents, and children working side by side.', ['family:', 'family,', 'family;', 'family'], 'punctuation', 'hard', 'A colon introduces the elaboration that follows the complete clause.'),
  G('Scientists once believed that adult brains could not grow new ', ' recent studies have overturned that view.', ['neurons, but', 'neurons but', 'neurons, however', 'neurons; but'], 'boundaries', 'medium', 'A comma plus the coordinating conjunction “but” correctly joins two independent clauses.'),
  G('The physicist Chien-Shiung Wu, whose experiments disproved a long-held law of ', ' was awarded the Wolf Prize in 1978.', ['physics,', 'physics', 'physics;', 'physics—and'], 'boundaries', 'medium', 'The nonessential clause set off by the comma after “Wu” must be closed with a matching comma.'),
  G('The council debated whether to widen the road or ', ' a bicycle lane instead.', ['to add', 'adding', 'they should add', 'the addition of'], 'parallelism', 'medium', '“Whether to widen…or to add” keeps the two infinitives parallel.'),
  G('The new species of frog is tiny, ', ' and remarkably loud for its size.', ['brightly colored,', 'brightly colored', 'brightly colored;', 'and brightly colored,'], 'punctuation in series', 'easy', 'Items in a series of three adjectives are separated by commas.'),
  G('Many of the ', ' in the archive were written in a shorthand that only a few scholars can read.', ['diaries', 'diary’s', 'diaries’', 'diarys'], 'plurals and possessives', 'easy', 'A plural noun with no possession takes no apostrophe: “diaries.”'),
  G('If the bridge ', ' completed on schedule, the ferry service will be discontinued next spring.', ['is', 'was', 'were', 'will be'], 'verb tense', 'medium', 'A conditional clause about a future event uses the present tense: “if the bridge is completed.”'),
  G('The choir ', ' its final concert of the season on Saturday and will begin rehearsals for next year in September.', ['performed', 'perform', 'performing', 'have performed'], 'subject-verb agreement', 'medium', 'The collective noun “choir” is singular; “performed” matches the past-time context.'),
]

const T = (passage, options, difficulty, explanation) => ({ passage, options, difficulty, explanation })
export const transitionItems = [
  T('Most desert plants conserve water by opening the pores in their leaves only at night. [[blank]] a few species take the opposite approach, absorbing carbon dioxide during the day and relying on deep roots to replace the water they lose.', ['However,', 'For example,', 'In addition,', 'As a result,'], 'easy', 'The second sentence contrasts with the first, so “However” is the logical transition.'),
  T('The town’s population doubled after the railroad arrived in 1871. [[blank]] the number of shops on Main Street grew from six to more than forty within a decade.', ['Consequently,', 'Nevertheless,', 'In other words,', 'Similarly,'], 'easy', 'The growth of shops is a result of the population increase.'),
  T('Coral bleaching occurs when water temperatures rise even a degree or two above normal. [[blank]] a heat wave in 2016 turned large stretches of the reef bone-white in a matter of weeks.', ['For instance,', 'Even so,', 'By contrast,', 'Meanwhile,'], 'easy', 'The second sentence gives an example of the general claim.'),
  T('Early mapmakers often filled unexplored regions with imaginary mountains and rivers. [[blank]] a blank space on a map was thought to reflect poorly on the mapmaker’s knowledge.', ['After all,', 'Otherwise,', 'Likewise,', 'Finally,'], 'medium', 'The second sentence explains the reason for the practice; “After all” introduces a justification.'),
  T('The proposed dam would generate enough electricity to power two hundred thousand homes. [[blank]] it would flood a valley that is home to several endangered species, a cost that critics say outweighs the benefit.', ['On the other hand,', 'Accordingly,', 'In fact,', 'Specifically,'], 'medium', 'The sentence presents a competing consideration, so a contrast transition is needed.'),
  T('Bees communicate the location of flowers through a “waggle dance” whose angle indicates direction. [[blank]] the duration of the dance indicates distance: the longer the waggle, the farther the flowers.', ['Furthermore,', 'Instead,', 'Nonetheless,', 'To be sure,'], 'medium', 'The second sentence adds a second feature of the dance.'),
  T('Marathon runners typically consume carbohydrates during a race to maintain their energy. [[blank]] cyclists on multi-day tours eat frequently while riding to avoid depleting their reserves.', ['Similarly,', 'However,', 'In particular,', 'Therefore,'], 'easy', 'The cyclists’ practice parallels the runners’; “Similarly” fits.'),
  T('The museum had planned to reopen its sculpture garden in May. [[blank]] flooding in April damaged the walkways, and the opening was pushed back to autumn.', ['Unfortunately,', 'For this reason,', 'Granted,', 'In summary,'], 'easy', 'The flood is an unfortunate development that thwarted the plan.'),
  T('Some historians credit the printing press with launching the scientific revolution. [[blank]] printed books did more than spread ideas; they allowed scientists in different cities to compare identical diagrams and tables for the first time.', ['Indeed,', 'Conversely,', 'Regardless,', 'Subsequently,'], 'hard', 'The second sentence intensifies and elaborates the first claim; “Indeed” signals emphasis.'),
  T('The company’s first electric truck was too expensive for most buyers. [[blank]] its second model, built with cheaper batteries, sold out within a month of its release.', ['By contrast,', 'For that reason,', 'In the same way,', 'Of course,'], 'medium', 'The second model’s success contrasts with the first model’s failure.'),
  T('The study’s participants were all college students in a single city. [[blank]] its findings may not apply to older adults or to people in rural areas.', ['Thus,', 'Besides,', 'Nevertheless,', 'Previously,'], 'medium', 'The limited sample leads to the conclusion about limited applicability.'),
  T('The novelist spent years researching medieval shipbuilding before writing a single sentence. [[blank]] she interviewed sailors, examined shipwrecks, and learned to tie dozens of historical knots.', ['Specifically,', 'Even so,', 'In contrast,', 'Hence,'], 'easy', 'The second sentence specifies what the research involved.'),
  T('Antibiotics have saved countless lives since the 1940s. [[blank]] their overuse has bred bacteria that no longer respond to them, a problem doctors now describe as a global emergency.', ['At the same time,', 'For example,', 'In conclusion,', 'Likewise,'], 'medium', 'The sentence adds a simultaneous drawback; “At the same time” captures the tension.'),
]

const S = (notes, goal, options, difficulty, explanation) => ({ notes, goal, options, difficulty, explanation })
export const synthesisItems = [
  S(['The Great Green Wall is an African-led project launched in 2007.', 'Its goal is to plant a belt of trees and restore land across the Sahel region.', 'The belt is planned to stretch about 8,000 kilometers, from Senegal to Djibouti.', 'As of 2022, roughly 18 percent of the planned area had been restored.', 'Restored areas have shown improved soil quality and new sources of income for farmers.'], 'emphasize the scale of the project', ['Launched in 2007, the Great Green Wall is planned to stretch about 8,000 kilometers across Africa, from Senegal to Djibouti.', 'Restored areas of the Great Green Wall have shown improved soil quality.', 'The Great Green Wall has given farmers new sources of income since 2007.', 'By 2022, roughly 18 percent of the Great Green Wall had been restored.'], 'easy', 'Only the first choice conveys the project’s enormous size (8,000 km, coast to coast).'),
  S(['Wangari Maathai was a Kenyan environmentalist and political activist.', 'In 1977, she founded the Green Belt Movement.', 'The movement paid rural women to plant trees, combining conservation with economic opportunity.', 'By 2004, the movement had planted more than 30 million trees.', 'Maathai received the Nobel Peace Prize in 2004.'], 'introduce Maathai’s movement to an audience unfamiliar with it', ['In 1977, Kenyan environmentalist Wangari Maathai founded the Green Belt Movement, which paid rural women to plant trees.', 'Maathai’s movement had planted more than 30 million trees by 2004.', 'Wangari Maathai received the Nobel Peace Prize in 2004.', 'The Green Belt Movement combined conservation with economic opportunity, which is why it succeeded.'], 'easy', 'The first choice names the founder, the movement, its date, and what it did—the essentials for an unfamiliar audience.'),
  S(['Researchers compared two methods of teaching a foreign language.', 'Method A used traditional grammar drills.', 'Method B used conversation with native speakers.', 'After six months, students using Method B scored 22 percent higher on a speaking test.', 'Students using Method A scored 8 percent higher on a written grammar test.'], 'present a balanced summary of the study’s results', ['After six months, students who practiced conversation scored higher on a speaking test, while students who used grammar drills scored higher on a written grammar test.', 'Conversation with native speakers is clearly the better way to learn a language, as the 22 percent advantage shows.', 'Method A, which used grammar drills, produced an 8 percent advantage on a written test.', 'Researchers compared two methods of teaching a foreign language over six months.'], 'medium', 'Only the first choice reports both outcomes without favoring one method.'),
  S(['The Voyager 1 spacecraft was launched in 1977.', 'It carries a gold-plated record containing sounds and images from Earth.', 'The record includes greetings in 55 languages and 90 minutes of music.', 'In 2012, Voyager 1 became the first human-made object to enter interstellar space.', 'Its signals now take more than 22 hours to reach Earth.'], 'emphasize how far Voyager 1 has traveled', ['Voyager 1 is now so distant that its signals take more than 22 hours to reach Earth, and in 2012 it became the first human-made object to enter interstellar space.', 'Voyager 1 carries a gold-plated record with greetings in 55 languages.', 'Launched in 1977, Voyager 1 carries 90 minutes of music from Earth.', 'The gold-plated record on Voyager 1 contains sounds and images from Earth.'], 'easy', 'The 22-hour signal delay and interstellar milestone both convey distance.'),
  S(['Ada Lovelace (1815–1852) was an English mathematician.', 'She wrote notes on Charles Babbage’s proposed Analytical Engine.', 'Her notes included an algorithm for computing Bernoulli numbers.', 'Many historians consider this algorithm the first computer program.', 'The Analytical Engine was never built during her lifetime.'], 'explain why Lovelace is significant to the history of computing', ['Lovelace’s notes on the Analytical Engine included an algorithm for computing Bernoulli numbers, which many historians consider the first computer program.', 'Ada Lovelace was an English mathematician who lived from 1815 to 1852.', 'The Analytical Engine, which Lovelace wrote about, was never built during her lifetime.', 'Lovelace wrote notes on a machine proposed by Charles Babbage.'], 'medium', 'The first choice links her work to the “first computer program,” the source of her significance.'),
  S(['Sourdough bread is leavened with a starter of wild yeast and bacteria rather than commercial yeast.', 'A starter must be “fed” with flour and water regularly.', 'Some bakeries maintain starters that are over 100 years old.', 'The bacteria produce lactic acid, which gives the bread its tangy flavor.', 'Sourdough takes 12 to 24 hours to rise, compared with 1 to 2 hours for bread made with commercial yeast.'], 'contrast sourdough with bread made with commercial yeast', ['Unlike bread made with commercial yeast, which rises in 1 to 2 hours, sourdough is leavened with wild yeast and bacteria and takes 12 to 24 hours to rise.', 'Some bakeries maintain sourdough starters that are more than 100 years old.', 'The bacteria in a sourdough starter produce lactic acid, giving the bread a tangy flavor.', 'A sourdough starter must be fed regularly with flour and water.'], 'medium', 'The first choice sets the two kinds of bread side by side and states the difference.'),
  S(['The Tuskegee Airmen were the first Black military pilots in the United States.', 'They trained at Tuskegee Institute in Alabama beginning in 1941.', 'They flew more than 15,000 missions in World War II.', 'Their bomber-escort record was among the best of any fighter group.', 'In 2007, the group was awarded the Congressional Gold Medal.'], 'emphasize the Airmen’s combat achievements', ['The Tuskegee Airmen flew more than 15,000 missions in World War II, and their bomber-escort record was among the best of any fighter group.', 'The Tuskegee Airmen trained at Tuskegee Institute in Alabama beginning in 1941.', 'In 2007, the Tuskegee Airmen were awarded the Congressional Gold Medal.', 'The Tuskegee Airmen were the first Black military pilots in the United States.'], 'easy', 'Missions flown and escort record are combat achievements; the other choices describe training or recognition.'),
  S(['Deep-sea anglerfish live at depths where no sunlight reaches.', 'Female anglerfish have a glowing lure on their heads that attracts prey.', 'The glow is produced by bacteria living in the lure.', 'Male anglerfish are much smaller and have no lure.', 'Some male anglerfish attach permanently to a female and depend on her for nutrients.'], 'explain how the anglerfish’s lure produces light', ['The glow of the anglerfish’s lure comes from bacteria that live inside it.', 'Female anglerfish use a glowing lure on their heads to attract prey.', 'Male anglerfish, which are much smaller than females, lack the glowing lure.', 'Deep-sea anglerfish live where no sunlight reaches, so their lure is useful.'], 'easy', 'Only the first choice explains the source of the light.'),
]
